[project]
name = "g-maker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.84.0",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
    "yt-dlp>=2025.5.22",
]
